version: "1"

services:
  xskt-bot:
    image: hieuphq/xskt-bot:0.1
    environment:
      - VERIFY_TOKEN=${VERIFY_TOKEN}
      - PAGE_ACCESS_TOKEN=${PAGE_ACCESS_TOKEN}
      #- VIRTUAL_PROTO=http
      #- HTTPS_METHOD=redirect
      #- HTTPS_METHOD=nohttp
      - VIRTUAL_HOST=presta.kalimtab.com
      #- LETSENCRYPT_HOST=presta.kalimtab.com
      #- LETSENCRYPT_EMAIL=hieupq@dwarvesv.com
    expose:
      - 80

networks:
  default:
    external:
      name: nginx-proxy
    